### ISSUE TITLE
tcpLUA_wrap.c:3724: _wrap_tcp_stream_clear: Assertion `!0x1 || usr->own == 1' failed

### ISSUE THREAD

**Issue by jihadinho** [haka-security/haka#34]
Hi,

I'm running the following script over a pcap of 17GB(around 600k flows).

```
root@System-U14LTS:~/work# cat luascript/http-stream-streamed.lua
local rem = require("regexp/pcre")
local tcp_connection = require('protocol/tcp_connection')
local http = require('protocol/http')
http.install_tcp_rule(80)
http.install_tcp_rule(80)
http.install_tcp_rule(2096)
http.install_tcp_rule(8080)
local re1 = rem.re:compile('^.*%.[^%%]+$', rem.re.CASE_INSENSITIVE)
local re2 = rem.re:compile("([^%/.]+)$|([^%/]+)(%.[^%/.]+)$", rem.re.CASE_INSENSITIVE)
haka.rule {
        hook = http.events.receive_data,
        options = {
        streamed = true,
        },
        eval = function (http, iter, dir)
        if http.request ~= nil then
                local split_uri = http.request.split_uri:normalize()
                if re2:match(http.request.uri) then
                        local res, startpos, endpos = re2:match(split_uri.path)
                        filename = string.sub(split_uri.path,startpos+1,endpos)
                        local file = io.open("/root/work/download/" .. filename, "w")
                        for sub in iter:foreach_available() do
                                file:write(sub:asstring())
                        end
                        file:close()
                end
        end
end
}
```

I get the following error. Below you can find the backtrace.

```
root@System-U14LTS:~/work# gdb hakapcap
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from hakapcap...done.
(gdb) run luascript/http-stream-streamed.lua /space/roho_ro.pcap --debug > roho.out
Starting program: /root/work/haka_0.3.0_source/make/out/usr/local/bin/hakapcap luascript/ht                                                                                                  tp-stream-streamed.lua /space/roho_ro.pcap --debug > roho.out
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
hakapcap: /root/work/haka_0.3.0_source/make/modules/protocol/tcp/tcpLUA_wrap.c:3724: _wrap_                                          tcp_stream_clear: Assertion `!0x1 || usr->own == 1' failed.

Program received signal SIGABRT, Aborted.
0x00007ffff74eacc9 in __GI_raise (sig=sig@entry=6)
    at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56      ../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff74eacc9 in __GI_raise (sig=sig@entry=6)
    at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff74ee0d8 in __GI_abort () at abort.c:89
#2  0x00007ffff74e3b86 in __assert_fail_base (
    fmt=0x7ffff7634830 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n",
    assertion=assertion@entry=0x7ffff56608dc "!0x1 || usr->own == 1",
    file=file@entry=0x7ffff565fc88 "/root/work/haka_0.3.0_source/make/modules/protocol/tcp/                                                                                                  tcpLUA_wrap.c", line=line@entry=3724,
    function=function@entry=0x7ffff5661c70 <__PRETTY_FUNCTION__.6882> "_wrap_tcp_stream_cle                                                                                                  ar") at assert.c:92
#3  0x00007ffff74e3c32 in __GI___assert_fail (
    assertion=0x7ffff56608dc "!0x1 || usr->own == 1",
    file=0x7ffff565fc88 "/root/work/haka_0.3.0_source/make/modules/protocol/tcp/tcpLUA_wrap                                                                                                  .c", line=3724,
    function=0x7ffff5661c70 <__PRETTY_FUNCTION__.6882> "_wrap_tcp_stream_clear")
    at assert.c:101
#4  0x00007ffff5657e2a in _wrap_tcp_stream_clear (L=0x40000378)
    at /root/work/haka_0.3.0_source/make/modules/protocol/tcp/tcpLUA_wrap.c:3724
#5  0x00007ffff791521b in lj_BC_FUNCC ()
   from /root/work/haka_0.3.0_source/make/out/usr/local/lib/libhaka.so.0
#6  0x00007ffff78f6bfa in lua_pcall (L=0x40000378, nargs=1, nresults=1, errfunc=3)
    at lj_api.c:1052
---Type <return> to continue, or q <return> to quit---
#7  0x00007ffff78b8dd1 in lua_transition_callback (state_machine=0x8073160,
    _data=0x61fc50) at /root/work/haka_0.3.0_source/make/lib/haka/lua/hakaLUA_wrap.c:3637
#8  0x00007ffff78983c1 in do_transition (instance=0x8073160, trans=0x61fb78)
    at /root/work/haka_0.3.0_source/lib/haka/state_machine.c:317
#9  0x00007ffff7898d95 in state_machine_instance_finish (instance=0x8073160)
    at /root/work/haka_0.3.0_source/lib/haka/state_machine.c:512
#10 0x00007ffff78990d9 in state_machine_instance_fail (instance=0x8073160)
    at /root/work/haka_0.3.0_source/lib/haka/state_machine.c:597
#11 0x00007ffff7898e83 in state_machine_instance_update (instance=0x8073160,
    newstate=0x7ffff7bb7600 <_state_machine_fail_state>)
    at /root/work/haka_0.3.0_source/lib/haka/state_machine.c:543
#12 0x00007ffff78987d2 in state_machine_enter_state (instance=0x8073160, state=0x61fae0)
    at /root/work/haka_0.3.0_source/lib/haka/state_machine.c:392
#13 0x00007ffff7898f67 in state_machine_instance_update (instance=0x8073160,
    newstate=0x61fae0) at /root/work/haka_0.3.0_source/lib/haka/state_machine.c:558
#14 0x00007ffff78b94da in state_machine_instance__update (self=0x8073160, state=0x61fae0)
    at /root/work/haka_0.3.0_source/make/lib/haka/lua/hakaLUA_wrap.c:3799
#15 0x00007ffff78d80c5 in _wrap_state_machine_instance_update (L=0x40000378)
    at /root/work/haka_0.3.0_source/make/lib/haka/lua/hakaLUA_wrap.c:12484
#16 0x00007ffff791521b in lj_BC_FUNCC ()
   from /root/work/haka_0.3.0_source/make/out/usr/local/lib/libhaka.so.0
#17 0x00007ffff78f6bfa in lua_pcall (L=0x40000378, nargs=1, nresults=0, errfunc=6)
---Type <return> to continue, or q <return> to quit---
    at lj_api.c:1052
#18 0x0000000000403b4b in filter_wrapper (state=0x609170, pkt=0xe338fb0)
    at /root/work/haka_0.3.0_source/src/haka/thread.c:84
#19 0x00000000004046d7 in thread_main_loop (_state=0x609170)
    at /root/work/haka_0.3.0_source/src/haka/thread.c:312
#20 0x0000000000404ed0 in thread_pool_start (pool=0x609110)
    at /root/work/haka_0.3.0_source/src/haka/thread.c:509
#21 0x0000000000403870 in start () at /root/work/haka_0.3.0_source/src/haka/app.c:183
#22 0x0000000000403241 in main (argc=2, argv=0x7fffffffe358)
    at /root/work/haka_0.3.0_source/src/haka/hakapcap.c:253
(gdb)
```

Here you may find the last output after dropping the last packet. 

```
debug packet:    dropping packet id=4003310
debug states:    http: leave transition on state 'response'
debug states:    http: finish from state 'response'
debug states:    http: finish transition on state 'response'
debug states:    http: leave transition on state 'request'
debug states:    http: finish from state 'request'
debug states:    http: finish transition on state 'request'
debug states:    http: leave transition on state 'request'
debug states:    http: finish from state 'request'
debug states:    http: finish transition on state 'request'
debug states:    http: leave transition on state 'request'
debug states:    http: finish from state 'request'
debug states:    http: finish transition on state 'request'
debug states:    http: leave transition on state 'request'
debug states:    http: finish from state 'request'
debug states:    http: finish transition on state 'request'
debug states:    http: leave transition on state 'request'
debug states:    http: finish from state 'request'
debug states:    http: finish transition on state 'request'
debug states:    http: leave transition on state 'request'
debug states:    http: finish from state 'request'
debug states:    http: finish transition on state 'request'
debug states:    http: leave transition on state 'request'
debug states:    http: finish from state 'request'
debug states:    http: finish transition on state 'request'
debug states:    http: leave transition on state 'request'
debug states:    http: finish from state 'request'
debug states:    http: finish transition on state 'request'
debug states:    http: leave transition on state 'request'
debug states:    http: finish from state 'request'
debug states:    http: finish transition on state 'request'
debug states:    http: leave transition on state 'request'
debug states:    http: finish from state 'request'
debug states:    http: finish transition on state 'request'
debug states:    http: leave transition on state 'request'
debug states:    http: finish from state 'request'
debug states:    http: finish transition on state 'request'
debug states:    http: leave transition on state 'request'
debug states:    http: finish from state 'request'
debug states:    http: finish transition on state 'request'
debug states:    http: leave transition on state 'request'
debug states:    http: finish from state 'request'
debug states:    http: finish transition on state 'request'
debug states:    http: leave transition on state 'request'
debug states:    http: finish from state 'request'
debug states:    http: finish transition on state 'request'
debug states:    http: leave transition on state 'request'
debug states:    http: finish from state 'request'
debug states:    http: finish transition on state 'request'
error lua:       state machine: invalid buffer iterator
stack traceback:
        [C]: in function 'clear'
        ...aka_0.3.0_source/modules/protocol/tcp/tcp_connection.lua:472: in function 'clearstream'
        ...aka_0.3.0_source/modules/protocol/tcp/tcp_connection.lua:173: in function 'execute'
        /root/work/haka_0.3.0_source/lib/haka/lua/lua/state.lua:163: in function </root/work/haka_0.3.0_source/lib/haka/lua/lua/state.lua:159>
        [C]: in function 'update'
        ...ork/haka_0.3.0_source/lib/haka/lua/lua/state_machine.lua:142: in function 'trigger'
        ...aka_0.3.0_source/modules/protocol/tcp/tcp_connection.lua:568: in function 'drop'
        ...aka_0.3.0_source/modules/protocol/tcp/tcp_connection.lua:675: in function 'drop'
        /root/work/haka_0.3.0_source/lib/haka/lua/lua/dissector.lua:86: in function '_trigger_receive'
        ...aka_0.3.0_source/modules/protocol/tcp/tcp_connection.lua:515: in function 'push'
        ...
        /root/work/haka_0.3.0_source/lib/haka/lua/lua/dissector.lua:116: in function </root/work/haka_0.3.0_source/lib/haka/lua/lua/dissector.lua:115>
        [C]: in function 'xpcall'
        /root/work/haka_0.3.0_source/lib/haka/lua/lua/dissector.lua:90: in function 'receive'
        /root/work/haka_0.3.0_source/lib/haka/lua/lua/dissector.lua:116: in function </root/work/haka_0.3.0_source/lib/haka/lua/lua/dissector.lua:115>
        [C]: in function 'xpcall'
        /root/work/haka_0.3.0_source/lib/haka/lua/lua/dissector.lua:90: in function 'receive'
        /root/work/haka_0.3.0_source/lib/haka/lua/lua/dissector.lua:116: in function </root/work/haka_0.3.0_source/lib/haka/lua/lua/dissector.lua:115>
        [C]: in function 'xpcall'
        /root/work/haka_0.3.0_source/lib/haka/lua/lua/dissector.lua:90: in function 'receive'
        [string "raw"]:64: in function <[string "raw"]:63>
debug states:    tcp: fail transition on state 'reset'
debug states:    tcp: leave transition on state 'reset'
debug states:    http: leave transition on state 'request'
debug states:    http: finish from state 'request'
debug states:    http: finish transition on state 'request'
debug states:    tcp: finish from state 'reset'
debug states:    tcp: finish transition on state 'reset'
```

Could you please take a look and let me know what the problem is? If you need any other info please tell me. I did not use
`cmake -DBUILD=Debug <path-to-haka-source>`

**Comment by paulfariello** [comment]
Hi,

it seems this issue is related with the last one you opened. We are trying to reproduce.

**Comment by jihadinho** [comment]
Hi, 

OK, but i'm using the fix you provided in my last question.
